resolver 127.0.0.11 valid=5s;
server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
    location /video/ {
        alias /usr/share/nginx/html/video/;
    }
    location /backend/ {
        set $backend http://streamflix-api:9898;
        proxy_pass $backend;
        rewrite ^/backend/(.*) /$1 break;
    }
    location /svc/api/ {
        set $api http://streamflix-api:9898;
        proxy_pass $api;
        rewrite ^/svc/api/(.*) /$1 break;
    }
    location /svc/catalog/ {
        set $catalog http://streamflix-catalog:9898;
        proxy_pass $catalog;
        rewrite ^/svc/catalog/(.*) /$1 break;
    }
    location /svc/streaming/ {
        set $streaming http://streamflix-streaming:9898;
        proxy_pass $streaming;
        rewrite ^/svc/streaming/(.*) /$1 break;
    }
    location /svc/payments/ {
        set $payments http://streamflix-payments:9898;
        proxy_pass $payments;
        rewrite ^/svc/payments/(.*) /$1 break;
    }
    location /prom/ {
        set $prom http://prometheus:9090;
        proxy_pass $prom;
        rewrite ^/prom/(.*) /$1 break;
    }
}
