global:
  scrape_interval: 5s

scrape_configs:
  - job_name: api-gateway
    static_configs:
      - targets: ['streamflix-api:9898']

  - job_name: catalog
    static_configs:
      - targets: ['streamflix-catalog:9898']

  - job_name: streaming
    static_configs:
      - targets: ['streamflix-streaming:9898']

  - job_name: payments
    static_configs:
      - targets: ['streamflix-payments:9898']

  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']
